controller_list:
  - name: fake_robot_arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
